config/routes.rb
Rails.application.routes.draw do
	root 'widgets#index'
	resources :widgets, only: [:index, :show ]

end

app/models/property.rb
class Property < ActiveRecord::Base
	belongs_to :widget


#	validate name in some list

end

app/models/widget.rb
class Widget < ActiveRecord::Base
	has_many :properties

	searchable do

		string :property_keys, :multiple => true do
			properties.collect(&:key)
		end

		#	:multiple => true works, so need to use arrays
		dynamic_string :properties, :multiple => true do
			#	loop over properties and build a hash.
			#	properties.inject({}) do |hash, property|
			#		if( hash.has_key?( property.key.to_sym ) )
			#			hash[property.key.to_sym].push( property.value )
			#		else
			#			hash.merge!(property.key.to_sym => [property.value])
			#		end
			#		hash
			#	end

			#	This is simpler.  Set default value to array.
			properties.inject( Hash.new {|h,k| h[k] = [] } ) do |hash, property|
				hash[property.key.to_sym].push( property.value )
				hash
			end
		end

		#	Can I also do ...
		#	dynamic_integer :properties do
		#		...
		#	end
		#	... for select properties that would be better indexed as integers?
		#
		#	No.  Looks like I would need a different name for each block.
		#	

	end
end
__END__


How to identify dynamic fields to facet on
https://github.com/sunspot/sunspot/issues/606


Could have a taken_at attribute on the properties, but can't index them.

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController

	def index
puts params.inspect
		@search = Widget.search do
			dynamic( :properties ) do

				#  loop over all given keys and facet them
				Widget.search{ facet :property_keys 
						}.facet(:property_keys).rows.collect(&:value).each do |kvp_facet|

					if params.has_key?( "properties:#{kvp_facet}" )	
						with( kvp_facet, params[ "properties:#{kvp_facet}" ] )
					end
					
					facet( kvp_facet )

				end

#				with( :color,  'yellow' )
			end
		end
	end

	def show
		@widget = Widget.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PolyProperty</title>
<link href="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/themes/base/jquery-ui.css" media="screen" rel="stylesheet" type="text/css" />

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js" type="text/javascript"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js" type="text/javascript"></script>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/widgets/index.html.erb
<%= content_tag(:div, class: 'table') do %>
<%= content_tag(:div, class: 'row') do %>
<%= content_tag(:div, id: 'refine') do %>
	<%= form_tag( widgets_path, :method => :get ) do %>
		<%= submit_tag "Search Widgets", :name => nil %><br/>
	
		<%#	preserve the order and direction on next search %>
		<%# could also save in session as do elsewhere? %>
		<%= hidden_field_tag :order, params[:order] %>
		<%= hidden_field_tag :dir, params[:dir] %>
	
		<%= content_tag(:div, class: 'facets') do %>
		<% @search.facets.each do |facet| -%>
			<% next if facet.rows.empty? -%><%# don't show empty facets -%>
	
			<% style, icon = if( params[facet.name] )
				["display:block;", "ui-icon-triangle-1-s"]
			else
				[                      nil, "ui-icon-triangle-1-e"]
			end %>
	
			<%= content_tag(:div, class: 'facet_toggle') do %>
				<% non_blank_row_count = facet.rows.reject{|r|r.value.blank?}.length %>
				<% facet_label = facet.name.to_s %>
				<%= content_tag(:span,'&nbsp;'.html_safe, class: "ui-icon #{icon}") %>
				<%= link_to("#{facet_label}&nbsp;(#{non_blank_row_count})".html_safe, 
					'javascript:void()') %>
			<% end %><%# content_tag(:div, class: 'toggle') do %>

			<%= content_tag(:div, id: facet.name, class: 'facet_field', style: style) do %>
				<%= content_tag(:ul, class: 'facet_field_values') do %>
					<% facet.rows.each do |row| %>
						<% next if row.value.blank? %>
						<% label = row.value %>
						<%= content_tag(:li) do %>
							<%# if options[:radio] %>
								<%#= radio_button_tag( "#{facet.name}[]", row.value,
										[params[facet.name]].flatten.include?(row.value.to_s),
										{ :id => "#{facet.name}_#{row.value.html_friendly}" } ) %>
							<%# else %>
								<%= check_box_tag( "#{facet.name}[]", row.value, 
										[params[facet.name]].flatten.include?(row.value.to_s),
										{ :id => "#{facet.name}_#{row.value.html_friendly}" } ) %>
							<%# end %>
							<%= label_tag "#{facet.name}_#{row.value.html_friendly}",
								"<span>#{label}</span>&nbsp;(&nbsp;#{row.count}&nbsp;)".html_safe  %>
						<% end %><%# content_tag(:li, %>
					<% end %><%# facet.rows.each %>
				<% end %><%# content_tag(:ul, %>
			<% end %><%# content_tag(:div, id: facet.name) do %>
	
		<% end -%><%# @search.facets.each do |facet| -%>
		<% end %><%# content_tag(:div, class: 'facets') do %>
	
	
		<%= content_tag(:div, class: 'field_wrapper') do %>
			<%= label_tag( :per_page, 'per page (html only) ' )%>
			<%= select_tag( :per_page, options_for_select([25,50,100], params[:per_page]||50) )%>
		<% end %><%# content_tag(:div, class: 'field_wrapper') do %>

	<% end %><%# form_tag -%>
<% end %><%# content_tag(:div, id: 'refine') do %>

<%= content_tag(:div, id: 'results') do %>
	<% unless @search.results.empty? %>
		<table><thead><tr>
			<th>&nbsp;</th>
			<th>Name</th>
			<th>Description</th>
		</tr></thead><tbody>
			<% @search.results.each do |result| %>
				<tr class='row'>
					<td><%= link_to result.id, result %></td>
					<td><%= result.name %></td>
					<td><%= result.description %></td>
				</tr>
			<% end %>
		</tbody></table>
		<br/><%= will_paginate(@search.hits) %>
		<p class='page_info'>Displaying page <%=@search.hits.current_page%> of 
			<%=@search.hits.total_pages%> out of <%=@search.total%> results</p>
	<% else %>
		<p>No results</p>
	<% end %>
<% end %><%# content_tag(:div, id: 'results') do %>
<% end %><%# content_tag(:div, class: 'table_row') do %>
<% end %><%# content_tag(:div, class: 'table') do %>

app/views/widgets/show.html.erb
<div class='widget'>
	<p><%= @widget.name %></p>
	<p><%= @widget.description %></p>
<% unless @widget.properties.empty? %>
	<table><thead>
		<tr><th>key</th><th>value</th></tr>
	</thead><tbody>
	<% @widget.properties.each do |property| %>
	<tr>
		<td><%= property.key %></td>
		<td><%= property.value %></td>
	</tr>
	<% end %><%# @widget.properties.each do |property| %>
	</tbody></table>
<% end %>
</div><!-- class='widget' -->